"""Datos curados a mano, sin dependencia de ninguna base de datos: retos
default para un grupo nuevo y sugerencias de canciones por género."""

DEFAULT_RETOS: list[list[str]] = [
    ["Canta agachado toda la canción", "Fácil", "Normal"],
    ["Cambia la letra por algo gracioso en el coro", "Medio", "Creativo"],
    ["Baila sin cantar los primeros 15 segundos", "Fácil", "Normal"],
    ["Cántale la canción a alguien del grupo mirándolo a los ojos", "Medio", "Picante"],
    ["Todo el grupo debe hacer los coros contigo", "Fácil", "Grupo"],
    ["Inventa una coreografía en 10 segundos y úsala toda la canción", "Difícil", "Creativo"],
    ["Canta con acento de otro país", "Medio", "Creativo"],
    ["Elige a alguien para que sea tu dueto sorpresa", "Medio", "Grupo"],
    ["Si te equivocas en la letra, debes repetir la estrofa bailando", "Difícil", "Picante"],
    ["Regala un piropo cantado a alguien del público antes de empezar", "Fácil", "Picante"],
    ["Canta esta canción como si fueras del género contrario al tuyo", "Medio", "Creativo"],
    ["Canta con un estilo de voz totalmente opuesto al tuyo (agudo si sos grave, grave si sos agudo)", "Difícil", "Creativo"],

    # Los 12 de arriba dejaban categorías de 2 retos: al filtrar por "Normal"
    # o por "Grupo" salía siempre el mismo. Estos 21 emparejan las cuatro
    # categorías en 8-9 cada una, que alcanza para una noche entera sin que
    # se note la repetición.
    ["Canta la primera estrofa con los ojos cerrados", "Fácil", "Normal"],
    ["Sostén el micrófono con la mano que no usas normalmente", "Fácil", "Normal"],
    ["Canta de espaldas al público hasta que llegue el coro", "Fácil", "Normal"],
    ["No puedes soltar el micrófono ni apoyarlo hasta terminar", "Medio", "Normal"],
    ["Canta sentado en el piso toda la canción", "Fácil", "Normal"],
    ["Cada vez que digas la palabra que más se repite en la canción, levanta la mano", "Medio", "Normal"],

    ["Dedícale la canción a alguien del grupo y di por qué antes de empezar", "Medio", "Picante"],
    ["Elige a alguien para que te acompañe al frente, aunque no cante nada", "Fácil", "Picante"],
    ["Antes de empezar, confiesa la canción que te da vergüenza que te guste", "Medio", "Picante"],
    ["Si desafinas, el grupo elige tu próxima canción", "Difícil", "Picante"],
    ["Termina la canción de rodillas, como si fuera la balada más trágica del mundo", "Medio", "Picante"],

    ["Canta la canción como si estuvieras narrando un partido de fútbol", "Difícil", "Creativo"],
    ["Reemplaza todas las vocales por la letra 'i' cuando llegue el coro", "Difícil", "Creativo"],
    ["Susurra toda la estrofa y grita el coro", "Medio", "Creativo"],
    ["Presenta la canción como locutor de radio antes de empezar", "Fácil", "Creativo"],

    ["El grupo elige una palabra prohibida: si la cantas, todos gritan", "Medio", "Grupo"],
    ["Todos tienen que bailar sentados mientras cantas", "Fácil", "Grupo"],
    ["Elige a dos personas para que sean tus bailarines de fondo", "Fácil", "Grupo"],
    ["El grupo canta el coro y tú solo las estrofas", "Fácil", "Grupo"],
    ["El primero que se ría canta la siguiente contigo", "Medio", "Grupo"],
    ["Todos aplauden al ritmo hasta que termines", "Fácil", "Grupo"],

    # Categoría aparte y no mezclada en "Picante" a propósito: no todas las
    # noches se toma (una reunión de trabajo, gente manejando, quien no bebe),
    # y teniéndola separada el grupo la incluye o la saca de un toque en vez
    # de tener que borrar reto por reto.
    ["Shot de afinación: toma 1 shot antes de empezar para calentar las cuerdas", "Fácil", "Shots"],
    ["El culpable paga: quien agregó esta canción a la lista toma 1 shot solidario contigo", "Fácil", "Shots"],
    ["Veredicto del jurado: al terminar el grupo vota con el pulgar, y si gana el pulgar abajo tomas 1 shot", "Medio", "Shots"],
    ["Shot doble de escape: puedes pasarle esta canción a otro, pero pagas 2 shots de penalización", "Medio", "Shots"],
    ["Shot cruzado: elige a alguien y tomen un shot con los brazos entrelazados justo antes del coro", "Fácil", "Shots"],
    ["El brindis dramático: pausa antes del coro final, da un discurso emotivo de 15 segundos y brinda con todos", "Medio", "Shots"],
    ["Ruleta rusa: gira una botella al terminar, y a quien apunte toma un shot contigo", "Fácil", "Shots"],
    ["Castigo por risa: si te da un ataque de risa y dejas de cantar más de 3 segundos, pagas 1 shot al final", "Medio", "Shots"],
    ["La ronda de la victoria: si logras que toda la sala cante el coro con los brazos arriba, todos toman menos tú", "Difícil", "Shots"],
    ["Doble o nada: al terminar pide votación. Si es unánime mandas 1 shot a quien quieras; si una sola persona vota en contra, te lo tomas tú", "Difícil", "Shots"],
    ["Shot por gallo: marca una raya cada vez que se te quiebre la voz y toma un shot por cada dos rayas", "Medio", "Shots"],
    ["Bautizo del micrófono: el que canta después de ti elige tu trago y tú eliges el suyo", "Fácil", "Shots"],
    ["Shot del olvido: si tienes que mirar la pantalla más de tres veces porque te perdiste, tomas 1 shot", "Medio", "Shots"],
    ["Brindis por estrofa: antes de cada estrofa levantas el vaso y todos brindan. El que no levante, toma", "Medio", "Shots"],
    ["El precio del aplauso: si nadie aplaude al terminar tomas 1 shot, pero si aplauden de pie eliges a dos que tomen", "Medio", "Shots"],
    ["Shot a ciegas: alguien del grupo te prepara un shot sin decirte qué es y lo tomas antes del último coro", "Difícil", "Shots"],
    ["Cadena de shots: eliges a alguien, esa persona elige a otra y esa a una tercera. Los tres toman contigo al final", "Fácil", "Shots"],
    ["Multa por celular: cualquiera que mire el celular mientras cantas paga 1 shot", "Fácil", "Shots"],
    ["Dueto forzado: canta con quien tengas a la derecha, y si cualquiera de los dos se equivoca toman ambos", "Medio", "Shots"],
    ["Impuesto al desafinado: el que se ría de cómo cantas toma 1 shot, pero si desafinas feo lo tomas tú", "Medio", "Shots"],
    ["La última nota: si sostienes la última nota más de 5 segundos, todos toman un shot en tu honor", "Difícil", "Shots"],
]

# Sugerencias de canciones populares por género, para el modal de "agregar
# canción" (chips de un click). Curada a mano — no depende de cuota de
# ninguna API externa. El link queda vacío a propósito: el usuario lo
# completa buscando en YouTube o pegándolo manualmente.
SUGERENCIAS_POR_GENERO: dict[str, list[tuple[str, str]]] = {
    "Pop": [
        ("Shape of You", "Ed Sheeran"),
        ("Blinding Lights", "The Weeknd"),
        ("Levitating", "Dua Lipa"),
    ],
    "Rock": [
        ("Livin' on a Prayer", "Bon Jovi"),
        ("Zombie", "The Cranberries"),
        ("De Musica Ligera", "Soda Stereo"),
    ],
    "Balada": [
        ("Perfect", "Ed Sheeran"),
        ("Un Beso", "Aventura"),
        ("Amor Eterno", "Rocio Durcal"),
    ],
    "Reggaeton": [
        ("Danza Kuduro", "Don Omar"),
        ("Gasolina", "Daddy Yankee"),
        ("Vivir Mi Vida", "Marc Anthony"),
    ],
    "Cumbia": [
        ("La Cumbia del Rio", "Los Angeles Azules"),
        ("El Sonidito", "Hechizeros Band"),
        ("Cumbia Sobre el Rio", "Selena"),
    ],
    "Salsa": [
        ("Vivir Mi Vida", "Marc Anthony"),
        ("La Vida es un Carnaval", "Celia Cruz"),
        ("Pedro Navaja", "Ruben Blades"),
    ],
    "Norteña": [
        ("El Rey", "Vicente Fernandez"),
        ("Cielito Lindo", "Ana Gabriel"),
        ("Volver Volver", "Vicente Fernandez"),
    ],
}


# --- Colecciones temáticas ---------------------------------------------------
#
# Agrupan el catálogo por "vibra" o por momento de la noche en vez de por
# género. Existen por dos razones concretas:
#
# 1. El campo genero es texto libre y en la base real hay 60+ valores distintos
#    para 221 canciones ("Pop Rock / Funk", "Merengue / Fusion", "salsa" en
#    minuscula). Como filtro no sirve; como dato suelto de una canción, sí.
# 2. En el salón, quien escanea el QR no sabe qué cantar. "Buscá por título" le
#    sirve a quien ya decidió; el que no decidió necesita una puerta de entrada
#    ("estoy con despecho", "quiero que cante toda la mesa").
#
# Una canción entra a una colección si coincide por CUALQUIERA de tres vías:
# artista, palabra clave del genero, o título curado. Es a propósito generoso:
# con catálogos de 50-100 temas, una colección que solo mire títulos curados
# devuelve dos canciones y queda muerta. Nada de esto se guarda en la base, así
# que funciona sobre los catálogos que ya existen sin migrar ni etiquetar nada.
#
# "canciones" cumple doble función: es el pack que el dueño puede cargar de un
# click, y a la vez son títulos que hacen match si ya los tenía cargados.
#
# El orden importa: es el que ve el usuario, y arriba van las más obvias.

COLECCIONES: list[dict] = [
    {
        "id": "cortavenas",
        "nombre": "Las Cortavenas",
        "emoji": "💔",
        "descripcion": "Despecho puro. Para cuando la balada es terapia.",
        "color": "from-blue-600 to-indigo-700",
        "artistas": [
            "José José", "Juan Gabriel", "Rocío Dúrcal", "Marco Antonio Solís",
            "Los Bukis", "Ricardo Arjona", "Sin Bandera", "Camila", "Reik",
            "Ana Gabriel", "Amanda Miguel", "Yuri", "Los Pasteles Verdes",
            "Ricardo Montaner", "Cristian Castro", "Alejandro Sanz",
            "Franco de Vita", "Luis Miguel", "Ha*Ash", "Jesse & Joy",
                    "Eros Ramazzotti", "Laura Pausini", "Alex Ubago", "Ha Ash", "Kalimba", "Noel Schajris", "Antonio Cartagena", "Pedro Fernandez",
        ],
        "generos": ["balada", "bolero"],
        "canciones": [
            ("El Triste", "José José", "Balada"),
            ("Amar y Querer", "José José", "Balada"),
            ("La Incondicional", "Luis Miguel", "Balada"),
            ("Amor Eterno", "Rocío Dúrcal", "Balada"),
            ("Si Nos Dejan", "Luis Miguel", "Balada"),
            ("Tu Cárcel", "Los Bukis", "Balada"),
            ("Y Cómo Es Él", "José Luis Perales", "Balada"),
            ("Entre el Mar y una Estrella", "Thalía", "Balada"),
            ("Te Vi Venir", "Sin Bandera", "Balada"),
            ("Mientes", "Camila", "Balada"),
            ("Noviembre Sin Ti", "Reik", "Balada"),
            ("Historia de un Amor", "Los Pasteles Verdes", "Balada"),
            ("Corazón Partío", "Alejandro Sanz", "Balada"),
            ("Te Amo", "Franco de Vita", "Balada"),
        ],
    },
    {
        "id": "salsa",
        "nombre": "Salsa Sensual & Baile",
        "emoji": "💃",
        "descripcion": "De la romántica a la brava. Nadie se queda sentado.",
        "color": "from-rose-500 to-red-600",
        "artistas": [
            "Marc Anthony", "Frankie Ruiz", "Eddie Santiago", "Grupo Niche",
            "Willie Colón", "Rubén Blades", "Celia Cruz", "Jerry Rivera",
            "Gilberto Santa Rosa", "La India", "Maelo Ruiz", "Tito Nieves",
            "Héctor Lavoe", "Oscar D'León", "Víctor Manuelle", "N'Klabe",
                    "Luis Enrique", "Jerry Rivera", "Tito Rojas", "Rey Ruiz", "Charlie Zaa", "Son by Four", "Grupo Gale", "DLG", "Adolescent's Orquesta",
        ],
        "generos": ["salsa", "guaracha"],
        "canciones": [
            ("Vivir Mi Vida", "Marc Anthony", "Salsa"),
            ("Valió la Pena", "Marc Anthony", "Salsa"),
            ("La Vida es un Carnaval", "Celia Cruz", "Salsa"),
            ("Cali Pachanguero", "Grupo Niche", "Salsa"),
            ("Gotas de Lluvia", "Grupo Niche", "Salsa"),
            ("Desnúdate Mujer", "Frankie Ruiz", "Salsa"),
            ("Tú Con Él", "Frankie Ruiz", "Salsa"),
            ("Lluvia", "Eddie Santiago", "Salsa"),
            ("Pedro Navaja", "Rubén Blades", "Salsa"),
            ("Idilio", "Willie Colón", "Salsa"),
            ("Cuenta Conmigo", "Jerry Rivera", "Salsa"),
            ("Conteo Regresivo", "Gilberto Santa Rosa", "Salsa"),
            ("El Gran Varón", "Willie Colón", "Salsa"),
            ("Te Conozco Bien", "Marc Anthony", "Salsa"),
        ],
    },
    {
        "id": "rock_espanol",
        "nombre": "Rock en Español Clásico",
        "emoji": "🎸",
        "descripcion": "Los 80 y 90 que todos se saben aunque digan que no.",
        "color": "from-orange-500 to-red-600",
        "artistas": [
            "Soda Stereo", "Enanitos Verdes", "Héroes del Silencio", "Caifanes",
            "Maná", "Los Prisioneros", "Hombres G", "Duncan Dhu", "La Ley",
            "Café Tacvba", "Bunbury", "Fito Páez", "Charly García",
            "Gustavo Cerati", "Attaque 77", "La Renga", "Los Fabulosos Cadillacs",
            "El Cuarteto de Nos", "Molotov", "Zoé",
        ],
        "generos": ["rock en espanol", "rock latino", "ska"],
        "canciones": [
            ("De Música Ligera", "Soda Stereo", "Rock en Español"),
            ("Persiana Americana", "Soda Stereo", "Rock en Español"),
            ("Lamento Boliviano", "Enanitos Verdes", "Rock en Español"),
            ("Entre Dos Tierras", "Héroes del Silencio", "Rock en Español"),
            ("La Flaca", "Jarabe de Palo", "Rock en Español"),
            ("Rayando el Sol", "Maná", "Rock en Español"),
            ("Oye Mi Amor", "Maná", "Rock en Español"),
            ("Afuera", "Caifanes", "Rock en Español"),
            ("La Célula Que Explota", "Caifanes", "Rock en Español"),
            ("El Baile de los que Sobran", "Los Prisioneros", "Rock en Español"),
            ("Devuélveme a Mi Chica", "Hombres G", "Rock en Español"),
            ("Cien Gaviotas", "Duncan Dhu", "Rock en Español"),
            ("El Duelo", "La Ley", "Rock en Español"),
            ("Matador", "Los Fabulosos Cadillacs", "Ska / Rock Latino"),
        ],
    },
    {
        "id": "cumbia",
        "nombre": "Cumbia Fiestera",
        "emoji": "🎉",
        "descripcion": "Sonidera, chicha y tecnocumbia. La que levanta la mesa.",
        "color": "from-yellow-400 to-orange-500",
        "artistas": [
            "Los Ángeles Azules", "Grupo 5", "Agua Marina", "Armonía 10",
            "Corazón Serrano", "Los Mirlos", "Ráfaga", "Damas Gratis",
            "Selena", "Los Ángeles Negros", "Aniceto Molina", "Sonora Dinamita",
            "Antología", "Chacalón", "Los Shapis", "Grupo Néctar",
                    "Sonido 2000", "Papillon", "Explosion de Iquitos", "Combinacion de La Habana", "Hermanos Yaipen", "Los Mirlos", "Grupo Nectar", "Zaperoko",
        ],
        "generos": ["cumbia", "chicha", "tecnocumbia", "sonidera", "cuarteto"],
        "canciones": [
            ("Cómo Te Voy a Olvidar", "Los Ángeles Azules", "Cumbia"),
            ("Nunca Es Suficiente", "Los Ángeles Azules", "Cumbia"),
            ("Motor y Motivo", "Grupo 5", "Cumbia Peruana"),
            ("Parranda", "Grupo 5", "Cumbia Peruana"),
            ("Paloma Ajena", "Agua Marina", "Cumbia Peruana"),
            ("Ambulante", "Agua Marina", "Cumbia Peruana"),
            ("Mi Niña Bonita", "Armonía 10", "Cumbia Peruana"),
            ("Enamórate de Mí", "Corazón Serrano", "Cumbia Peruana"),
            ("Cariñito", "Los Mirlos", "Cumbia Peruana"),
            ("La Danza de los Mirlos", "Los Mirlos", "Cumbia Peruana"),
            ("Mentirosa", "Ráfaga", "Cumbia"),
            ("Una Cerveza", "Ráfaga", "Cumbia"),
            ("El Sonidito", "Hechizeros Band", "Cumbia Sonidera"),
            ("Como la Flor", "Selena", "Cumbia / Tex-Mex"),
        ],
    },
    {
        "id": "reggaeton_old",
        "nombre": "Reggaetón Old School",
        "emoji": "🔥",
        "descripcion": "Del 2004 al 2012. El perreo con el que crecieron.",
        "color": "from-fuchsia-500 to-purple-600",
        "artistas": [
            "Daddy Yankee", "Don Omar", "Wisin & Yandel", "Tego Calderón",
            "Zion & Lennox", "Héctor el Father", "Calle 13", "Arcángel",
            "Plan B", "Ivy Queen", "Nicky Jam", "De La Ghetto", "Alexis & Fido",
            "Baby Rasta & Gringo", "RKM & Ken-Y", "Tito El Bambino",
        ],
        "generos": ["reggaeton", "dembow", "perreo"],
        "canciones": [
            ("Gasolina", "Daddy Yankee", "Reggaetón"),
            ("Rompe", "Daddy Yankee", "Reggaetón"),
            ("Danza Kuduro", "Don Omar", "Reggaetón"),
            ("Dile", "Don Omar", "Reggaetón"),
            ("Rakata", "Wisin & Yandel", "Reggaetón"),
            ("Yo Voy", "Zion & Lennox", "Reggaetón"),
            ("Metele Sazón", "Tego Calderón", "Reggaetón"),
            ("Atrévete-te-te", "Calle 13", "Reggaetón"),
            ("Es Un Secreto", "Plan B", "Reggaetón"),
            ("Quiero Bailar", "Ivy Queen", "Reggaetón"),
            ("Down", "RKM & Ken-Y", "Reggaetón"),
            ("El Amor", "Tito El Bambino", "Reggaetón"),
            ("Noche de Sexo", "Wisin & Yandel", "Reggaetón"),
            ("Chambonea", "Nicky Jam", "Reggaetón"),
        ],
    },
    {
        "id": "divas",
        "nombre": "Divas del Desahogo",
        "emoji": "👑",
        "descripcion": "Himnos de mujeres que no piden permiso.",
        "color": "from-pink-500 to-rose-600",
        "artistas": [
            "Shakira", "Paulina Rubio", "Thalía", "Gloria Trevi",
            "Alejandra Guzmán", "Jenni Rivera", "Ana Gabriel", "Amanda Miguel",
            "Yuri", "Selena", "Rocío Dúrcal", "Gloria Estefan", "La India",
            "Olga Tañón", "Lady Gaga", "Adele", "Whitney Houston", "Beyoncé",
            "Alicia Keys", "Rihanna",
                    "Laura Pausini", "Chenoa", "Malú", "Natalia Lafourcade", "Julieta Venegas", "Mon Laferte", "Christina Aguilera", "Celine Dion",
        ],
        "generos": [],
        "canciones": [
            ("Ciega, Sordomuda", "Shakira", "Pop Latino"),
            ("Antología", "Shakira", "Pop Latino"),
            ("Mi Buen Corazón", "Alejandra Guzmán", "Rock Pop"),
            ("Hacer el Amor con Otro", "Alejandra Guzmán", "Rock Pop"),
            ("Todos Me Miran", "Gloria Trevi", "Pop"),
            ("Pelo Suelto", "Gloria Trevi", "Pop"),
            ("Y Yo Sigo Aquí", "Paulina Rubio", "Pop"),
            ("Amor a la Mexicana", "Thalía", "Pop Latino"),
            ("Resulta", "Ana Gabriel", "Ranchera"),
            ("Simplemente Amigos", "Ana Gabriel", "Balada"),
            ("El Que Se Fue", "Amanda Miguel", "Balada"),
            ("Él Me Mintió", "Amanda Miguel", "Balada"),
            ("Detrás de Mi Ventana", "Yuri", "Balada"),
            ("I Will Survive", "Gloria Gaynor", "Disco"),
        ],
    },
    {
        "id": "a_gritos",
        "nombre": "Las que se Cantan a Gritos",
        "emoji": "🗣️",
        "descripcion": "Coro colectivo garantizado. Nadie canta solo esta.",
        "color": "from-emerald-500 to-teal-600",
        "artistas": [],
        "generos": ["himno"],
        "canciones": [
            ("Bohemian Rhapsody", "Queen", "Rock Clásico"),
            ("Don't Stop Me Now", "Queen", "Rock Clásico"),
            ("Livin' on a Prayer", "Bon Jovi", "Rock Clásico"),
            ("Don't Stop Believin'", "Journey", "Rock Clásico"),
            ("Zombie", "The Cranberries", "Rock Alternativo"),
            ("Color Esperanza", "Diego Torres", "Pop Latino"),
            ("La Bamba", "Ritchie Valens", "Rock"),
            ("Me Gustas Tú", "Manu Chao", "Rock Latino"),
            ("Hijo de la Luna", "Mecano", "Pop"),
            ("Mujer Contra Mujer", "Mecano", "Pop"),
            ("Rayando el Sol", "Maná", "Rock en Español"),
            ("La Camisa Negra", "Juanes", "Pop Latino"),
            ("Y Nos Dieron las Diez", "Joaquín Sabina", "Rock en Español"),
            ("Sweet Caroline", "Neil Diamond", "Pop Clásico"),
        ],
    },
    {
        "id": "ranchera",
        "nombre": "Tequila y Despecho",
        "emoji": "🍻",
        "descripcion": "Rancheras para gritar con el vaso en la mano.",
        "color": "from-amber-500 to-orange-600",
        "artistas": [
            "Vicente Fernández", "Alejandro Fernández", "José Alfredo Jiménez",
            "Antonio Aguilar", "Pedro Infante", "Javier Solís", "Pepe Aguilar",
            "Christian Nodal", "Banda MS", "Jenni Rivera", "Lucha Villa",
        ],
        "generos": ["ranchera", "mariachi", "banda", "norteña", "nortena", "corrido"],
        "canciones": [
            ("El Rey", "Vicente Fernández", "Ranchera"),
            ("Volver, Volver", "Vicente Fernández", "Ranchera"),
            ("Acá Entre Nos", "Vicente Fernández", "Ranchera"),
            ("Mujeres Divinas", "Vicente Fernández", "Ranchera"),
            ("Como Quien Pierde una Estrella", "Alejandro Fernández", "Ranchera"),
            ("Si Tú Supieras", "Alejandro Fernández", "Ranchera"),
            ("La Media Vuelta", "José Alfredo Jiménez", "Ranchera"),
            ("Ella", "José Alfredo Jiménez", "Ranchera"),
            ("Un Puño de Tierra", "Antonio Aguilar", "Ranchera"),
            ("Cielito Lindo", "Pedro Infante", "Ranchera"),
            ("Sombras Nada Más", "Javier Solís", "Bolero"),
            ("Directo al Corazón", "Pepe Aguilar", "Ranchera"),
            ("Adiós Amor", "Christian Nodal", "Ranchera"),
            ("Cielo Rojo", "Jenni Rivera", "Ranchera"),
        ],
    },
    {
        "id": "duetos",
        "nombre": "Solo de a Dos",
        "emoji": "👯",
        "descripcion": "Necesitan dos voces. Buscate cómplice antes de pedirla.",
        "color": "from-violet-500 to-purple-600",
        "artistas": ["Sin Bandera", "Jesse & Joy", "Ha*Ash", "Pimpinela"],
        "generos": ["dueto"],
        "canciones": [
            ("A Puro Dolor", "Son by Four", "Balada"),
            ("No Me Doy por Vencido", "Luis Fonsi", "Balada"),
            ("Vuelve", "Ricky Martin", "Balada"),
            ("Sabor a Mí", "Los Panchos", "Bolero"),
            ("Olvídame y Pega la Vuelta", "Pimpinela", "Balada"),
            ("Ese Hombre", "Pimpinela", "Balada"),
            ("Loco", "Enrique Iglesias", "Bachata"),
            ("Espacio Sideral", "Jesse & Joy", "Pop Latino"),
            ("Dónde Están Corazón", "Enrique Iglesias", "Pop Latino"),
            ("Te Quiero Tanto", "Ha*Ash", "Pop Latino"),
            ("Photograph", "Ed Sheeran", "Pop"),
            ("Shallow", "Lady Gaga", "Pop"),
            ("Islands in the Stream", "Kenny Rogers", "Pop Clásico"),
            ("Endless Love", "Lionel Richie", "Balada"),
        ],
    },
    {
        "id": "nostalgia_2000",
        "nombre": "Nostalgia de los 2000",
        "emoji": "📼",
        "descripcion": "La secundaria en una playlist. Duele bonito.",
        "color": "from-cyan-500 to-blue-600",
        "artistas": [
            "RBD", "Camila", "Reik", "Sin Bandera", "La Oreja de Van Gogh",
            "Britney Spears", "Backstreet Boys", "NSYNC", "Avril Lavigne",
            "Kudai", "Belanova", "Panda", "Zoé", "Fanny Lu", "Chino y Nacho",
            "Nelly Furtado", "Evanescence", "Linkin Park", "Maroon 5",
                    "Sandy y Junior", "OV7", "Moderatto", "Motel", "Nikki Clan", "Alex Ubago", "David Bisbal", "La 5a Estacion", "Lu", "MDO",
        ],
        "generos": [],
        "canciones": [
            ("Sálvame", "RBD", "Pop"),
            ("Nuestro Amor", "RBD", "Pop"),
            ("Rebelde", "RBD", "Pop"),
            ("Todo Cambió", "Camila", "Pop"),
            ("Coleccionista de Canciones", "Camila", "Pop"),
            ("Yo Quisiera", "Reik", "Pop"),
            ("Entre Tus Alas", "Camila", "Pop"),
            ("Rosas", "La Oreja de Van Gogh", "Pop"),
            ("La Playa", "La Oreja de Van Gogh", "Pop"),
            ("Sin Documentos", "Los Rodríguez", "Rock en Español"),
            ("Complicated", "Avril Lavigne", "Pop Rock"),
            ("Toxic", "Britney Spears", "Dance Pop"),
            ("I Want It That Way", "Backstreet Boys", "Pop"),
            ("Niña Bonita", "Chino y Nacho", "Pop Latino"),
        ],
    },
    {
        "id": "rock_ingles",
        "nombre": "Rock en Inglés Clásico",
        "emoji": "🤘",
        "descripcion": "Guitarras y estadio. Del 70 al 2000.",
        "color": "from-slate-500 to-gray-700",
        "artistas": [
            "Queen", "Bon Jovi", "Journey", "Guns N' Roses", "AC/DC",
            "Nirvana", "Oasis", "The Beatles", "The Rolling Stones", "Aerosmith",
            "Metallica", "Linkin Park", "Green Day", "Red Hot Chili Peppers",
            "The Cranberries", "Radiohead", "Coldplay", "U2", "Scorpions",
        ],
        "generos": ["hard rock", "grunge", "britpop", "rock clasico", "new wave"],
        "canciones": [
            ("We Will Rock You", "Queen", "Rock Clásico"),
            ("Sweet Child O' Mine", "Guns N' Roses", "Hard Rock"),
            ("Highway to Hell", "AC/DC", "Hard Rock"),
            ("Smells Like Teen Spirit", "Nirvana", "Grunge"),
            ("Wonderwall", "Oasis", "Britpop"),
            ("Hey Jude", "The Beatles", "Rock Clásico"),
            ("Let It Be", "The Beatles", "Rock Clásico"),
            ("Nothing Else Matters", "Metallica", "Hard Rock"),
            ("In the End", "Linkin Park", "Rock Alternativo"),
            ("Boulevard of Broken Dreams", "Green Day", "Rock Alternativo"),
            ("Wind of Change", "Scorpions", "Rock Clásico"),
            ("With or Without You", "U2", "Rock"),
            ("Yellow", "Coldplay", "Rock Alternativo"),
            ("Creep", "Radiohead", "Rock Alternativo"),
        ],
    },
    {
        "id": "peruano",
        "nombre": "Criollo y Peruano",
        "emoji": "🇵🇪",
        "descripcion": "De Chabuca al rock subte. La de la casa.",
        "color": "from-red-500 to-rose-600",
        "artistas": [
            "Mar de Copas", "Pedro Suárez-Vértiz", "Gian Marco", "Libido",
            "Amén", "Eva Ayllón", "Chabuca Granda", "Daniel F", "Leusemia",
            "We The Lion", "Bareto", "Los Doltons", "Lucía de la Cruz",
            "Arturo Zambo Cavero", "Los Pasteles Verdes",
                    "Antonio Cartagena", "Anna Carina", "Arena Hash", "Los Nosequien y los Nosecuantos", "Christian Yaipen", "Agua Bella", "Alvaro Rod", "Rio", "Frágil",
        ],
        "generos": ["criollo", "vals", "festejo"],
        "canciones": [
            ("Un Día Sin Sexo", "Mar de Copas", "Rock"),
            ("Vuelve", "Mar de Copas", "Rock"),
            ("Cuando Pienses en Volver", "Pedro Suárez-Vértiz", "Rock"),
            ("Los Globos del Cielo", "Pedro Suárez-Vértiz", "Rock"),
            ("Me Elevé", "Pedro Suárez-Vértiz", "Rock"),
            ("Canción de Amor", "Gian Marco", "Balada"),
            ("Hoy", "Gian Marco", "Balada"),
            ("Hembra", "Libido", "Rock"),
            ("Sed", "Libido", "Rock"),
            ("Fotografía", "Amén", "Rock"),
            ("Contigo Perú", "Arturo Zambo Cavero", "Criollo"),
            ("Y Se Llama Perú", "Arturo Zambo Cavero", "Criollo"),
            ("La Flor de la Canela", "Chabuca Granda", "Vals Criollo"),
            ("Regresa", "Eva Ayllón", "Criollo"),
        ],
    },
    {
        "id": "tropical",
        "nombre": "Tropical: Merengue y Bachata",
        "emoji": "🌴",
        "descripcion": "Merengue, vallenato y bachata. Calor de la costa.",
        "color": "from-teal-400 to-emerald-600",
        "artistas": [
            "Elvis Crespo", "Juan Luis Guerra", "Carlos Vives", "Chichi Peralta",
            "Olga Tañón", "Grupo Mania", "Aventura", "Romeo Santos",
            "Prince Royce", "Toño Rosario", "Wilfrido Vargas", "Los Hermanos Rosario",
            "Eddy Herrera", "Monchy & Alexandra", "Sergio Vargas",
        ],
        "generos": ["merengue", "vallenato", "bachata", "tropical"],
        "canciones": [
            ("Suavemente", "Elvis Crespo", "Merengue"),
            ("Píntame", "Elvis Crespo", "Merengue"),
            ("La Bilirrubina", "Juan Luis Guerra", "Merengue"),
            ("Burbujas de Amor", "Juan Luis Guerra", "Bachata"),
            ("Ojalá Que Llueva Café", "Juan Luis Guerra", "Merengue"),
            ("La Gota Fría", "Carlos Vives", "Vallenato"),
            ("La Tierra del Olvido", "Carlos Vives", "Vallenato"),
            ("Procura", "Chichi Peralta", "Merengue"),
            ("Es Mentiroso", "Olga Tañón", "Merengue"),
            ("Obsesión", "Aventura", "Bachata"),
            ("Un Beso", "Aventura", "Bachata"),
            ("Propuesta Indecente", "Romeo Santos", "Bachata"),
            ("Darte un Beso", "Prince Royce", "Bachata"),
            ("Hoja en Blanco", "Monchy & Alexandra", "Bachata"),
        ],
    },
    {
        "id": "pop_latino",
        "nombre": "Pop Latino Bailable",
        "emoji": "🕺",
        "descripcion": "Los hits que suenan en toda fiesta desde hace 20 años.",
        "color": "from-sky-400 to-cyan-600",
        "artistas": [
            "Chayanne", "Enrique Iglesias", "Ricky Martin", "Luis Fonsi",
            "Juanes", "Carlos Rivera", "La Quinta Estación", "La 5ª Estación",
            "Fanny Lu", "Gente de Zona", "Álvaro Soler", "Diego Torres",
            "Ricardo Montaner", "Sebastián Yatra", "Carlos Baute",
        ],
        "generos": ["pop latino"],
        "canciones": [
            ("Torero", "Chayanne", "Pop Latino"),
            ("Salomé", "Chayanne", "Pop Latino"),
            ("Provócame", "Chayanne", "Pop Latino"),
            ("Bailando", "Enrique Iglesias", "Pop Latino"),
            ("Bailamos", "Enrique Iglesias", "Pop Latino"),
            ("Súbeme la Radio", "Enrique Iglesias", "Pop Latino"),
            ("Livin' la Vida Loca", "Ricky Martin", "Pop Latino"),
            ("La Copa de la Vida", "Ricky Martin", "Pop Latino"),
            ("Despacito", "Luis Fonsi", "Pop Latino"),
            ("La Camisa Negra", "Juanes", "Pop Latino"),
            ("A Dios le Pido", "Juanes", "Pop Latino"),
            ("El Sol No Regresa", "La Quinta Estación", "Pop Latino"),
            ("Color Esperanza", "Diego Torres", "Pop Latino"),
            ("Sofía", "Álvaro Soler", "Pop Latino"),
        ],
    },
    {
        "id": "ochentas",
        "nombre": "Los 80 y la Disco",
        "emoji": "🕶️",
        "descripcion": "Sintetizador, brillo y pista. Imposible quedarse quieto.",
        "color": "from-purple-500 to-indigo-600",
        "artistas": [
            "Michael Jackson", "Madonna", "ABBA", "Bee Gees", "Village People",
            "a-ha", "Cyndi Lauper", "Tina Turner", "Whitney Houston",
            "Gloria Gaynor", "Donna Summer", "Earth, Wind & Fire", "Prince",
            "Wham!", "Modern Talking", "Miami Sound Machine", "The Weeknd",
            "Bruno Mars", "Mark Ronson", "Dua Lipa",
        ],
        "generos": ["disco", "synthpop", "funk", "new wave", "dance"],
        "canciones": [
            ("Billie Jean", "Michael Jackson", "Pop / Dance"),
            ("Beat It", "Michael Jackson", "Pop / Dance"),
            ("YMCA", "Village People", "Disco"),
            ("Dancing Queen", "ABBA", "Disco"),
            ("Stayin' Alive", "Bee Gees", "Disco"),
            ("Take On Me", "a-ha", "Synthpop"),
            ("Like a Prayer", "Madonna", "Pop"),
            ("Girls Just Want to Have Fun", "Cyndi Lauper", "Pop"),
            ("Simply the Best", "Tina Turner", "Pop"),
            ("I Will Survive", "Gloria Gaynor", "Disco"),
            ("September", "Earth, Wind & Fire", "Disco / Funk"),
            ("Uptown Funk", "Mark Ronson", "Funk / Pop"),
            ("Blinding Lights", "The Weeknd", "Synthpop"),
            ("Conga", "Miami Sound Machine", "Disco"),
        ],
    },
    {
        "id": "pop_ingles",
        "nombre": "Pop en Inglés Actual",
        "emoji": "🎧",
        "descripcion": "Lo que suena hoy. Del 2010 para acá.",
        "color": "from-lime-400 to-emerald-600",
        "artistas": [
            "The Weeknd", "Dua Lipa", "Ed Sheeran", "Bruno Mars", "Adele",
            "Billie Eilish", "Taylor Swift", "Harry Styles", "Coldplay",
            "Maroon 5", "Sia", "Justin Bieber", "Sam Smith", "Rihanna",
            "Katy Perry", "Meghan Trainor", "Shawn Mendes", "Olivia Rodrigo",
            "Ariana Grande", "Charlie Puth", "Imagine Dragons", "OneRepublic",
        ],
        "generos": ["pop alternativo", "indie pop"],
        "canciones": [
            ("Blinding Lights", "The Weeknd", "Synthpop"),
            ("Save Your Tears", "The Weeknd", "Pop"),
            ("Levitating", "Dua Lipa", "Dance Pop"),
            ("Don't Start Now", "Dua Lipa", "Dance Pop"),
            ("Shape of You", "Ed Sheeran", "Pop"),
            ("Perfect", "Ed Sheeran", "Pop"),
            ("Just the Way You Are", "Bruno Mars", "Pop"),
            ("Grenade", "Bruno Mars", "Pop"),
            ("Someone Like You", "Adele", "Pop"),
            ("Easy on Me", "Adele", "Pop"),
            ("Bad Guy", "Billie Eilish", "Pop Alternativo"),
            ("Shake It Off", "Taylor Swift", "Pop"),
            ("Love Story", "Taylor Swift", "Pop"),
            ("As It Was", "Harry Styles", "Pop"),
            ("Chandelier", "Sia", "Pop"),
            ("All About That Bass", "Meghan Trainor", "Pop"),
            ("Sugar", "Maroon 5", "Pop"),
            ("Believer", "Imagine Dragons", "Rock Alternativo"),
        ],
    },
    {
        "id": "urbano_nuevo",
        "nombre": "Urbano de Ahora",
        "emoji": "💥",
        "descripcion": "Lo que piden los que tenían 5 años con Gasolina.",
        "color": "from-violet-600 to-fuchsia-600",
        "artistas": [
            "Bad Bunny", "Karol G", "Rosalía", "Feid", "Rauw Alejandro",
            "J Balvin", "Maluma", "Ozuna", "Anuel AA", "Sech", "Myke Towers",
            "Peso Pluma", "Quevedo", "Bizarrap", "Shakira", "Becky G",
            "Natti Natasha", "Farruko", "Manuel Turizo",
        ],
        "generos": ["trap", "urbano"],
        "canciones": [
            ("Tití Me Preguntó", "Bad Bunny", "Reggaetón"),
            ("Me Porto Bonito", "Bad Bunny", "Reggaetón"),
            ("Callaíta", "Bad Bunny", "Reggaetón"),
            ("Bichota", "Karol G", "Reggaetón"),
            ("Provenza", "Karol G", "Reggaetón"),
            ("TQG", "Karol G", "Reggaetón"),
            ("Despechá", "Rosalía", "Reggaetón"),
            ("Todo de Ti", "Rauw Alejandro", "Reggaetón"),
            ("Normal", "Feid", "Reggaetón"),
            ("Mi Gente", "J Balvin", "Reggaetón"),
            ("Felices los 4", "Maluma", "Reggaetón"),
            ("Taki Taki", "Ozuna", "Reggaetón"),
            ("Otro Trago", "Sech", "Reggaetón"),
            ("La Bachata", "Manuel Turizo", "Bachata"),
            ("Pepas", "Farruko", "Reggaetón"),
            ("Ella Baila Sola", "Peso Pluma", "Corrido"),
        ],
    },
    {
        "id": "cine_tv",
        "nombre": "De Película",
        "emoji": "🎬",
        "descripcion": "Bandas sonoras, Disney y novelas. Nadie se resiste.",
        "color": "from-amber-400 to-yellow-600",
        "artistas": ["Celine Dion", "Elton John", "Whitney Houston"],
        "generos": ["banda sonora", "soundtrack", "disney"],
        "canciones": [
            ("My Heart Will Go On", "Celine Dion", "Balada"),
            ("I Will Always Love You", "Whitney Houston", "Balada"),
            ("Let It Go", "Idina Menzel", "Pop"),
            ("Un Mundo Ideal", "Aladdín", "Balada"),
            ("Bella y Bestia Son", "La Bella y la Bestia", "Balada"),
            ("El Ciclo Sin Fin", "El Rey León", "Pop"),
            ("Hakuna Matata", "El Rey León", "Pop"),
            ("Can You Feel the Love Tonight", "Elton John", "Balada"),
            ("(I've Had) The Time of My Life", "Dirty Dancing", "Pop"),
            ("You're the One That I Want", "Grease", "Pop"),
            ("Eye of the Tiger", "Survivor", "Rock Clásico"),
            ("Ghostbusters", "Ray Parker Jr.", "Pop"),
            ("A Whole New World", "Aladdin", "Balada"),
            ("No Se Habla de Bruno", "Encanto", "Pop"),
            ("Colors of the Wind", "Pocahontas", "Balada"),
        ],
    },
    {
        "id": "cierre",
        "nombre": "La Última de la Noche",
        "emoji": "🌅",
        "descripcion": "Para cerrar. Abrazo, brindis y luces prendidas.",
        "color": "from-indigo-500 to-violet-600",
        "artistas": [],
        "generos": [],
        "canciones": [
            ("Amor Eterno", "Juan Gabriel", "Balada"),
            ("Vivir Mi Vida", "Marc Anthony", "Salsa"),
            ("El Rey", "Vicente Fernández", "Ranchera"),
            ("Y Nos Dieron las Diez", "Joaquín Sabina", "Rock en Español"),
            ("Color Esperanza", "Diego Torres", "Pop Latino"),
            ("Contigo Perú", "Arturo Zambo Cavero", "Criollo"),
            ("La Vida es un Carnaval", "Celia Cruz", "Salsa"),
            ("Que Cante la Vida", "Gian Marco", "Balada"),
            ("Cielito Lindo", "Pedro Infante", "Ranchera"),
            ("My Way", "Frank Sinatra", "Pop Clásico"),
            ("Don't Stop Believin'", "Journey", "Rock Clásico"),
            ("Gracias a la Vida", "Violeta Parra", "Folk"),
            ("Cómo Te Voy a Olvidar", "Los Ángeles Azules", "Cumbia"),
            ("We Are the Champions", "Queen", "Rock Clásico"),
        ],
    },
    {
        "id": "nivel_dios",
        "nombre": "Nivel Dios",
        "emoji": "🎯",
        "descripcion": "Difíciles de verdad. Pedila solo si te la sabés.",
        "color": "from-purple-600 to-fuchsia-700",
        "artistas": [],
        "generos": [],
        "canciones": [
            ("Bohemian Rhapsody", "Queen", "Rock Clásico"),
            ("Hasta Que Te Conocí", "Juan Gabriel", "Balada"),
            ("La Incondicional", "Luis Miguel", "Balada"),
            ("El Triste", "José José", "Balada"),
            ("Vivo por Ella", "Andrea Bocelli", "Balada"),
            ("Se Me Olvidó Otra Vez", "Juan Gabriel", "Ranchera"),
            ("I Will Always Love You", "Whitney Houston", "Balada"),
            ("Rolling in the Deep", "Adele", "Pop"),
            ("Listen", "Beyoncé", "Pop"),
            ("Ciega, Sordomuda", "Shakira", "Pop Latino"),
            ("Atrévete-te-te", "Calle 13", "Reggaetón"),
            ("Sweet Child O' Mine", "Guns N' Roses", "Hard Rock"),
            ("Entre el Mar y una Estrella", "Thalía", "Balada"),
            ("Contigo Perú", "Arturo Zambo Cavero", "Criollo"),
        ],
    },
]
